# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5501f3bb5fd7b218f0d05a8e199e857257565c5afc821bcb5659be99a3bd48db9a37c1c0363c0aba54a2b7400129ea71b61a2e7157de897de5b4b0cc564b4fe0

test:
  secret_key_base: 2b91f773563c45296498519ab8adbbf0e9e66dd2348103442c19648eba0ab77616c9169aeb14f9d0f59a82a62404a69ad835a4f6b441e2912d9043a27319d7ee

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
